galaxy_info:
  author: Brandon Foos
  description: Ansible Role to install
  
  version: 0.1
  license:
    - MIT
  min_ansible_version: 1.2
  galaxy_tags: []

  platforms:
    - name: Rocky
      versions:
        - 8
        - 9

dependencies: []
